version: "3.0"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - es-net
    ports:
      - 9200:9200
  kibana:
    image: kibana-dev
    build:
      context: .
      args:
        HTTP_PROXY: $HTTP_PROXY
        HTTPS_PROXY: $HTTP_PROXY
        NO_PROXY: $NO_PROXY
      dockerfile: Dockerfile.kibana-dev
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    volumes:
      - ./kibana.dev.yml:/kibana/config/kibana.dev.yml
      - ./start-dev.sh:/kibana/start-dev.sh
      - ../:/kibana/plugins
networks:
  es-net:
    driver: bridge

# After container is running, connect using:
# docker-compose exec kibana bash
# ./start-dev.sh
