name: Build and Release Plugins

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compile TypeScript
        run: |
          yarn global add typescript
          cd data-builder/ && tsc --project tsconfig.json
          cd ../drilldown/ && tsc --project tsconfig.json
          cd ../legend/ && tsc --project tsconfig.json
      - name: Fetch Plugin Dependencies
        run: cd line-visualizer/ && yarn && cd ../radar-visualizer/ && yarn
      - name: Compress
        run: |
          mkdir kibana && cp -R line-visualizer/ kibana/ && zip -r line-visualizer-7.15.0.zip kibana/
          rm -r kibana/* && cp -R radar-visualizer/ kibana/ && zip -r radar-visualizer-7.15.0.zip kibana/
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            line-visualizer-7.15.0.zip
            radar-visualizer-7.15.0.zip
