name: Vis Plugin Builder

on:
  push:
    tags:
      - "*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compile Plugins
        run: cd line-visualizer/ && yarn && cd ../radar-visualizer/ && yarn
      - name: ZIP Plugins
        run: mkdir kibana && cp -R line-visualizer/ kibana/ && zip -r line-visualizer-7.15.0.zip kibana/
        run: rm -r kibana/* && cp -R radar-visualizer/ kibana/ && zip -r radar-visualizer-7.15.0.zip kibana/
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: | 
            line-visualizer-7.15.0.zip
            radar-visualizer-7.15.0.zip
